---
swagger: "2.0"
info:
  version: 1.0-SNAPSHOT
  title: “lesson 1”
basePath: /v1
paths:
  /accounts/{id}:
    get:
      description: Gets balance of account
      operationId: accounts/getBalance
      parameters:
       - in: path
         name: id
         required: true
         type: integer
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        200:
          description: empty response
  /accounts:
    post:
      description: Create an account
      operationId: accounts/createAccount
      consumes: 
      - application/json
      produces:
      - application/json
      responses:
        200:
          description: empty response
    get:
      description: query Customer ID
      operationId: accounts/queryAccounts
      parameters:
      - in: query
        name: customerId
        type: integer
        description: Customer ID
      consumes:
      - application/json
      produces: 
      - application/json
      responses: 
        200:
          description: empty
